/** Portal Form 131 Nature of Payment legend text (from official reference PDF). */
export const form131NatureLegend: Record<string, string> = {
  "1004": "Any payment of accumulated balance due to an employee",
  "1005": "Commission or brokerage - insurance",
  "1006": "Commission or brokerage - others",
  "1008": "Rent on machinery etc.- specified person",
  "1009": "Rent other than machinery etc.- specified person",
  "1011": "Payment on any consideration, not being consideration in kind, under the agreement referred to in section 67(14).",
  "1012": "Payment of compensation on acquisition of certain immovable property",
  "1013": "Income payable to a resident assessee in respect of Units of a specified Mutual Fund specified under Schedule VII or units from the Administrator of the",
  "1014": "Certain income in the form of interest from units of a business trust to a resident unit holder",
  "1015": "Certain income in the form of dividend from units of a business trust to a resident unit holder",
  "1016": "Certain income in the form of Renting from units of a business trust being a real estate investment trust to a resident unit holder",
  "1017": "Any income, other than that proportion of income which is exempt under Schedule V, in respect of units of an investment fund specified in section 224,",
  "1018": "Any income, in respect of an investment in a securitisation trust specified in section 221 to an investor.",
  "1019": "Any income by way of Interest on securities",
  "1020": "Any income by way of interest other than interest on securities, in case of deductee/payee is a senior citizen",
  "1021": "Any income by way of interest other than interest on securities, in case of deductee/payee is other than senior citizen",
  "1022": "Any income being interest other than interest on securities",
  "1023": "Any sum for carrying out any work (including supply of labour for carrying out any work) in pursuance of a contract between the contractor and a designate",
  "1024": "Any sum for carrying out any work (including supply of labour for carrying out any work) in pursuance of a contract between the contractor and a designate",
  "1026": "Any sum by way of (a) fees for technical services (not being a professional services); or (b) royalty in the nature of consideration for sale, distribution or",
  "1027": "Any sum by way of (a) fees for professional services; or (b) any sum referred to in section 26(2)(h)",
  "1028": "Any sum by way of remuneration or fees or commission by whatever name called, other than those on which tax is deductible under section 392, to a",
  "1029": "Any dividends (including on preference shares) declared.",
  "1030": "Any sum under a life insurance policy, including the sum allocated as bonus on such policy, other than the amount not includible in the total income under",
  "1031": "Any sum for purchase of any goods",
  "1033": "Any benefit or perquisite, whether convertible into money or not, arising from business or the exercise of a profession of any resident.",
  "1034": "Any benefit or perquisite, whether in cash or in kind or partly in cash and partly in kind, whether convertible into money or not, arising from business or the",
  "1035": "Sale of goods or provision of services by an e-commerce participant, facilitated by an e-commerce operator through its digital or electronic facility or",
  "1037": "Any sum by way of consideration for transfer of a virtual digital asset by other than Individual or Hindu Undivided Family.",
  "1038": "Any sum by way of consideration, whether in cash or in kind or partly in cash and partly in kind, for transfer of a virtual digital asset.",
  "1058": "Any income by way of winnings (other than winnings from SI. No. 2 of the table at section 393(3)) from (a) any lottery; or (b) crossword puzzle; or (c) card",
  "1059": "Any income by way of winnings (other than winnings from SI. No. 2 of the table at section 393(3)) from (a) any lottery; or (b) crossword puzzle; or (e) card",
  "1060": "Any income by way of winnings from online game.",
  "1061": "Any income by way of winnings from online games where consideration is made in kind or cash is not sufficient to meet the tax liability and tax has been",
  "1062": "Any income by way of winnings from any horse race.",
  "1063": "Any income, credited or paid to a person, who is or has been stocking, distributing, purchasing or selling lottery tickets, by way of commission,",
  "1064": "Payment of certain amounts in cash by bank/ post office / co-operative society to a deductee being a co-operative society",
  "1065": "Payment of certain amounts in cash by bank/ post office / co-operative society to a deductee being a person other than co-operative society",
  "1066": "Any amount referred to in section 80CCA(2)(a) of the Income-tax Act, 1961 (43 of 1961).",
  "1067": "Any sum in the nature of salary, remuneration, commission, bonus or interest paid to a partner of the firm or credited to his account (including capital",
  "1039": "Any income referred to in section 211.",
  "1040": "Any income by way of interest payable in respect of monies borrowed in foreign currency from a source outside India, (a) under a loan agreement or issue",
  "1041": "Any income by way of interest payable in respect of monies borrowed from a source outside India by way of issue of rupee denominated bond before the",
  "1042": "Any income by way of interest payable in respect of monies borrowed from a source outside India by way of issue of any long-term bond or rupee",
  "1043": "Any income by way of interest payable in respect of monies borrowed from a source outside India by way of issue of any long-term bond or rupee",
  "1044": "Any income by way of interest.",
  "1045": "Any distributed income referred to in section 223, being of the nature referred to in Schedule V [Table: Sl. No. 3.B(a)]",
  "1046": "Any distributed income referred to in section 223, being of the nature referred to in Schedule V [Table: Sl. No. 3.B(b)]",
  "1047": "Any unit holder, being a nonresident (not being a company) or a foreign company",
  "1048": "Any income, other than that proportion of income which is exempt under Schedule V [Table: Sl. No. 2], in respect of units of an investment fund specified",
  "1049": "Any income in respect of an investment in a securitisation trust specified in section 221.",
  "1050": "Any income (a) in respect of units of a Mutual Fund specified under Schedule VII [Table: Sl. No. 20] or [Table: Sl. No. 21]; or (b) from the specified",
  "1051": "Any income in respect of units referred to in section 208.",
  "1052": "Any income by way of long-term capital gains arising from the transfer of units referred to in section 208.",
  "1053": "Any income by way of interest or dividends in respect of bonds or Global Depository Receipts referred to in section 209.",
  "1054": "Any income by way of long-term capital gains arising from the transfer of bonds or Global Depository Receipts referred to in section 209.",
  "1055": "Any income in respect of securities referred to in section 210(1) [Table: Sl. No. 1].",
  "1056": "Any income in respect of securities referred to in section 210(1) [Table: Sl. No. 1].",
  "1057": "Any interest (not being interest referred to against serial numbers 2, 3, 4 and 5) or any other sum chargeable under the provisions of this Act, not being"
} as const
